s
DudaKristian/DepecheCode pull request #25
Opened 2021-11-13 20:48 UTC by o5o2472793

переназвала

2021-11-13 21:11 UTC, DudaKristian requested changes
Виправ, будь-ласка, моменти)

2021-11-13 21:11 UTC, DudaKristian commented on src/partials/customer-reviews.html
> +    <p class="advantatages__list-link">Nullam viverra consectetuer. Quisque cursus et, porttitor risus. Aliquam sem. In hendrerit <span></span> <br>
цей абзац відноситься до li.
і в кожної лі по 1 такому абзацу.
Також, тимчасово, 2 лі закоментуй, щоб нам з потока не виривались, а ми потім пришиємо їх до слайдера.

2021-11-13 21:11 UTC, DudaKristian commented on src/sass/components/_customer-reviews.scss
> +}
Дані стилі, прошу, також приведи під мобільну версію, або задай одразу медіа-правила під адаптив.

2021-11-14 00:00 UTC, o5o2472793 commented
внесла зміни

2021-11-14 08:42 UTC, DudaKristian commented
Ок, дивись, тепер тобі треба переназвати ще класи)) буде по БЕМ, де Б уже не advantages a customer-review.

2021-11-14 10:16 UTC, closed without merging