Adds _reset.scss 1.0
DudaKristian/DepecheCode pull request #3
Opened 2021-11-11 22:52 UTC by BohdanToder

Можна поки не Мержити в Мейн, завтра обсудим під час содзвону що ще сюди додаєм (якщо потрібно).

2021-11-11 23:20 UTC, ViktorBalko approved these changes

2021-11-12 00:07 UTC, ViktorBalko requested changes
hero-headder предлагаю заменить на hero-header. По значению слов получается, что у нас герой руководитель, вместо хедера) мелочь, но бросается в глаза

2021-11-12 08:17 UTC, BohdanToder commented
Тест

2021-11-12 12:47 UTC, DudaKristian commented
да, то мій тупняк =) Перейменую до вечірнього мітапа

2021-11-12 13:16 UTC, DudaKristian reviewed
Я б додав li i a text-style:none

2021-11-12 15:07 UTC, smirnypavel approved these changes

2021-11-12 15:10 UTC, DudaKristian commented on src/sass/main.scss
>  @import './components/hero-headder';
Я вже змінив

2021-11-12 16:37 UTC, YaroslavPlaksii91 requested changes
потрібно добавити list-style - none для списків, text-decoration - none для силок, outline - none для кнопок, силок і можливих майбутніх input, textarea

2021-11-12 16:37 UTC, YaroslavPlaksii91 commented on src/sass/base/_reset.scss
> +  width: 100%;
правильніше max-width

2021-11-12 17:17 UTC, smirnypavel approved these changes

2021-11-12 17:53 UTC, BohdanToder commented on src/sass/base/_reset.scss
> +  width: 100%;
Якщо буде можливість шарити свій екран то покажу чому width, а не max-width

2021-11-12 19:10 UTC, DudaKristian approved these changes

2021-11-12 19:11 UTC, merged